apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  ports:
  - port: 3306
# This port shouild match with the port on which the database is running
    protocol: TCP
  selector:
    app: database
  type: LoadBalancer