apiVersion: v1
kind: Pod
metadata:
  name: mypod-voulmesecret
spec:
  volumes:
    - name: foo
      secret:
        secretName: mysecret-manifest
## Provide the name of the secret
  containers:
  - name: volumesecret
## Provide the name of the volume type
    image: redis
    volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true